### ISSUE TITLE
Consider adding a diff mode

### ISSUE THREAD

**Issue by DavidSchinazi** [martinthomson/rfc-tidy#2]
My main use case for `rfc-tidy` is to diff two existing XML files. It looks something like this:

```sh
#!/bin/bash

if [ "$#" -ne 2 ]; then echo "Needs two params" ; exit 1 ; fi
TMP_FILE_1="$(mktemp /tmp/rfc-tidy-XXXXXX)"
TMP_FILE_2="$(mktemp /tmp/rfc-tidy-XXXXXX)"
rfc-tidy < "$1" > "$TMP_FILE_1"
rfc-tidy < "$2" > "$TMP_FILE_2"
git diff --no-index --word-diff=color "$TMP_FILE_1" "$TMP_FILE_2"
```

It would be great if we could instead have `rfc-tidy` do this directly in memory without having to write temporary files to disk

**Comment by martinthomson** [comment]
Have you tried something like:

`diff <(rfc-tidy a.xml) <(rfc-tidy b.xml)`?

**Comment by DavidSchinazi** [comment]
Oh neat, I hadn't thought of process substitution. For some reason that works for `diff` but not for `git diff`, and diff doesn't support word diff on my platform.

Happy:
```
$ diff -u <(rfc-tidy a.xml) <(rfc-tidy b.xml)
```

Sad:
```
$ git diff --no-index --word-diff=color -- <(rfc-tidy a.xml) <(rfc-tidy b.xml)

error: /dev/fd/63: unsupported file type
fatal: cannot hash /dev/fd/63
Traceback (most recent call last):
  File "/usr/local/bin/rfc-tidy", line 173, in <module>
    parser.parse(sys.argv[1])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-124/Python/Modules/pyexpat.c", line 461, in EndElement
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/usr/local/bin/rfc-tidy", line 148, in endElement
    self.flush(self.tags.pop())
  File "/usr/local/bin/rfc-tidy", line 114, in flush
    print(c, end="")
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by martinthomson** [comment]
Yeah, I get a different error, but it still fails.  Maybe git does some random access stuff.  

I was able to get `ccdiff` to accept this, which depends on a new package (it's available on Debian main).  I don't have a mac handy but homebrew seems to have `icdiff` and `ydiff` packages that claim to do the same thing.

**Comment by DavidSchinazi** [comment]
Sounds involved enough that I'm probably going to stick with the mktemp approach for now. It could be neat to use python to do the diff in-process using [`difflib`](https://docs.python.org/3/library/difflib.html) but that's probably too much effort for a limited result.
